### ISSUE TITLE
Error when installing in MacOS

### ISSUE THREAD

**Issue by mgab** [bmerry/birdisle-py#16]
I was able to install birdisle-py using `pip install birdisle` in docker containers running Linux Alpine 6.4.0 and Ubuntu 16.04. However, when trying to run the same command in MacOS Mojave 10.14.1 the building process fails giving the [following output](https://github.com/bmerry/birdisle-py/files/2667616/pip_install_birdisle.log).

The only clue I was able to find was on the README from fakeredis, that points out that [birdisle can only run on Linux](https://github.com/jamesls/fakeredis/#note-on-redis-py-3). I am not sure, though, as I was not able to find anything about this in the birdisle or birdisle-py repository.

Is it really not supported? if so, should we state it in the README and/or documentation? And otherwise, do you have any idea what is failing?

**Comment by g-abello** [comment]
Any update on this? I'm facing the same issue.

**Comment by bmerry** [comment]
Yes, it is only supported on Linux. I'm not developing birdisle further, but feel free to send in a PR to update the documentation.
