### ISSUE TITLE
Redis Version 3.3 introduced health_check_interval

### ISSUE THREAD

**Issue by serlachner** [bmerry/birdisle-py#18]
Redis version 3.3 introduced a new parameter `health_check_interval` that is not passed into `LocalSocketConnection`. Therefore tests are failing. A quick fix that worked on our side was to add `health_check_interval` to `LocalSocketConnection.__init__`.

Is it possible for you to take a look at this?

Cheers

**Comment by bmerry** [comment]
This should be fixed in 0.2.0, although I haven't specifically tested passing a health check interval.
