### ISSUE TITLE
Alpine Linux: libbirdisle.so.1: backtrace: symbol not found

### ISSUE THREAD

**Issue by kurczynski** [bmerry/birdisle-py#20]
I'm unable to run `birdisle` using the `python3.6-alpine` Docker image, it tells me that it's unable to find `backtrace`. This is the error I get:
```
  File "/usr/local/lib/python3.6/site-packages/birdisle/__init__.py", line 6, in <module>
    from . import _birdisle
ImportError: Error relocating /usr/local/lib/python3.6/site-packages/birdisle/.libs/libbirdisle.so.1: backtrace: symbol not found

```

However, it does seem to work when using the `python:3.6-slim` Docker image.

Searching around the internets suggests that it's caused by Alpine not having `glibc`.

**Comment by bmerry** [comment]
It sounds like you've found the solution: don't use Alpine/musl. `backtrace` is something that redis itself calls, and birdisle is just packaging up redis into a library, so there isn't much I can do about it.
