### ISSUE TITLE
publish wheel for python 3.8 on PyPI

### ISSUE THREAD

**Issue by rooterkyberian** [bmerry/birdisle-py#22]
I have encountered an issue where my library which is tested using birdisle-py cannot be tested under docker vanilla `python:3.8-slim` image because it lacks build utils required to compile birdisle-py from source.

Other than that wheels just save time so even if someone had build utils along python 3.8 they would still gain from this.

**Comment by bmerry** [comment]
I've released 0.2.0 with wheels up to 3.10.
